# This is a basic workflow to help you get started with Actions

name: Deploy DocFX from main branch to Webserver

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout repo
        uses: actions/checkout@v2

      - name: Build site with DocFX
        run: |
          cd "C:\actions-runner\_work\docfx_project\docfx_project"
          docfx docfx.json

      - name: Move existing website to temp location
        run: |
          $iiSFiles = ".config", ".f5config"
          $websitePath = "C:\inestserv\main\"
          $tempPath = "C:\Backup\main\main\"
          Get-ChildItem -Path $websitePath -Recurse | Where-Object {$iiSFiles -notcontains $_.Name} |  Move-Item -Destination $tempPath -Force -Verbose

      - name: Move DocFX site to IIS directory
        run: |
          $MoveItems = @{
            Path = "C:\actions-runner\_work\docfx_project\docfx_project\_site\*"
            Destination = "C:\inestserv\main\"
            Force = $true
            #PassThru = $true
            ErrorAction = "SilentlyContinue"
            Verbose = $true
            Confirm = $false
          }
          Move-Item @MoveItems

      - name: Backup existing website
        run: |
          $CompressArchive = @{
            Path = "C:\Backup\main\main\"
            DestinationPath = "C:\Backup\main\$((Get-Date).ToString("dd MM yyyy HH-mm-ss")).zip"
            CompressionLevel = "Fastest"
            ErrorAction = "SilentlyContinue"
            Force = $true
            Verbose = $true
          }
          Compress-Archive @CompressArchive

      - name: Remove temp backup drectory
        run: |
          $RemoveItem = @{
            Path = "C:\Backup\main\main\"
            ErrorAction = "SilentlyContinue"
            Force = $true
            Verbose = $true
          }
          Remove-Item -Recurse @RemoveItem
