# This is a basic workflow to help you get started with Actions

name: Deploy DocFX from staging branch to Webserver

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout repo
        uses: actions/checkout@v2

      - name: Backup existing website
        run: |
          $CompressArchive = @{
          Path = "C:\inestserv\staging\"
          DestinationPath = "C:\Backup\staging\$((Get-Date).ToString("dd MM yyyy HH-mm-ss")).zip"
          CompressionLevel = "Fastest"
          Force = $true
          Verbose = $true
          }
          Compress-Archive @CompressArchive

      - name: Build site with DocFX
        run: |
          cd "C:\actions-runner\_work\docfx_project\docfx_project"
          docfx docfx.json

      - name: Move DocFX site to IIS directory
        run: |
          cd "C:\actions-runner\_work\docfx_project\docfx_project"
          docfx docfx.json
