# This is a basic workflow to help you get started with Actions

name: DocFX Build and Publish

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  linux:
    name: Qt 4.8 on Linux
    runs-on: ubuntulatest
  
  
  windows:
    name: Qt 4.8 on Windows
    runs-on: windows-2019
